# Welcome to Jekyll!
#

# Site settings
title: CCKOREA Naming Vote
owner: Creative Commons Korea # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: thechunsik@cckorea.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vote.cckorea.org" # the base hostname & protocol for your site
permalink: "/blog/:title.html"
social:
  twitter: https://twitter.com/cckorea
  github: https://github.com/creativecommonskorea
  # linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/cckorea
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
